// code generated by claude.ai
import { useState, useEffect } from 'react';

export default function About() {
    const [activeSkill, setActiveSkill] = useState(null);
    const [floatingIndex, setFloatingIndex] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setFloatingIndex((prev) => (prev + 1) % 3);
        }, 2000);

        return () => clearInterval(interval);
    }, []);

    const skills = [
        { name: 'Frontend', level: 90, color: 'bg-[#f7b2ad]', icon: '💻' },
        { name: 'Design', level: 75, color: 'bg-purple-500', icon: '🎨' },
        { name: 'Backend', level: 80, color: 'bg-green-500', icon: '⚙️' },
        { name: 'Advocacy', level: 65, color: 'bg-pink-500', icon: '⚖️' },
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-[#e8bfff] via-[#ffb3e6] to-[#e8bfff] text-black overflow-hidden">
            <div className="relative z-10 max-w-6xl mx-auto px-6 py-16">
                {/* About Section */}
                <div className="mb-20 bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-white/20 transition-all duration-300 transform hover:scale-[1.02]">
                    <h2 className="text-3xl font-bold mb-6 text-black">About Me</h2>
                    <p className="text-black text-lg leading-relaxed mb-4">
                        I'm a passionate developer who loves creating beautiful, interactive experiences on the web.
                        With a background in both design and development, I bring ideas to life with clean code and
                        thoughtful user experiences.
                    </p>
                    <p className="text-black text-lg leading-relaxed">
                        When I'm not coding, you can find me exploring new coffee shops, playing guitar, or
                        working on my latest side project. I believe in continuous learning and pushing the
                        boundaries of what's possible on the web.
                    </p>
                </div>

                {/* GITHUB CHART! */}
                <div className="mb-20 bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-white/20 transition-all duration-300">
                    <h2 className="text-3xl font-bold mb-6 text-black">GitHub Activity</h2>
                    <div className="rounded-lg overflow-hidden bg-white/5 p-4">
                        <img
                            src="https://ghchart.rshah.org/charliharrold"
                            alt="GitHub Contribution Chart"
                            className="w-full"
                            style={{ imageRendering: 'crisp-edges' }}
                        />
                    </div>
                </div>

                {/* Skills Section */}
                <div className="mb-20">
                    <h2 className="text-3xl font-bold mb-8 text-center text-purple-400">Skills & Interests</h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {skills.map((skill, index) => (
                            <div
                                key={skill.name}
                                className="bg-white/5 backdrop-blur-lg rounded-xl p-6 border border-white/10 hover:border-white/20 transition-all duration-300 cursor-pointer"
                                onMouseEnter={() => setActiveSkill(index)}
                                onMouseLeave={() => setActiveSkill(null)}
                                style={{
                                    transform: activeSkill === index ? 'translateY(-8px)' : 'translateY(0)',
                                    boxShadow: activeSkill === index ? '0 20px 40px rgba(139,92,246,0.3)' : 'none',
                                }}
                            >
                                <div className="flex items-center gap-3 mb-4">
                                    <div className={`p-2 ${skill.color} rounded-lg text-2xl`}>
                                        {skill.icon}
                                    </div>
                                    <h3 className="text-xl font-semibold">{skill.name}</h3>
                                </div>
                                <div className="relative h-3 bg-white/10 rounded-full overflow-hidden">
                                    <div
                                        className={`h-full ${skill.color} rounded-full transition-all duration-1000 ease-out`}
                                        style={{
                                            width: activeSkill === index ? `${skill.level}%` : '0%',
                                        }}
                                    />
                                </div>
                                <div className="text-right mt-2 text-sm text-gray-400">
                                    {activeSkill === index && `${skill.level}%`}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Fun Facts */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {[
                        { emoji: '⚖️', title: 'Advocacy', desc: 'DETAILS FROM CLUBS' },
                        { emoji: '🚀', title: 'Projects', desc: '50+ completed' },
                        { emoji: '🎵', title: 'Playlists', desc: '100+ hours' },
                    ].map((fact, index) => (
                        <div
                            key={index}
                            className="bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10 text-center transform hover:scale-105 hover:rotate-1 transition-all duration-300 cursor-pointer"
                        >
                            <div className="text-5xl mb-3">{fact.emoji}</div>
                            <h3 className="text-xl font-bold mb-2">{fact.title}</h3>
                            <p className="text-black">{fact.desc}</p>
                        </div>
                    ))}
                </div>

            </div>
        </div>
    );
}