// code generated by claude.ai
import { useState, useEffect } from 'react';
import './About.css';

export default function About() {
    const [activeSkill, setActiveSkill] = useState(null);
    const [floatingIndex, setFloatingIndex] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setFloatingIndex((prev) => (prev + 1) % 3);
        }, 2000);

        return () => clearInterval(interval);
    }, []);

    const skills = [
        { name: 'Frontend', level: 90, color: 'bg-[#f7b2ad]', icon: '💻' },
        { name: 'Design', level: 75, color: 'bg-purple-500', icon: '🎨' },
        { name: 'Backend', level: 80, color: 'bg-green-500', icon: '⚙️' },
        { name: 'Advocacy', level: 65, color: 'bg-pink-500', icon: '⚖️' },
    ];

    return (
        <div className="about-container min-h-screen bg-gradient-to-br from-[#e8bfff] via-[#ffb3e6] to-[#e8bfff] text-black">
            <br />
            <div className="content relative z-10 max-w-6xl mx-auto px-6 py-16">
                {/* About Section */}
                <div className="mb-20 bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-white/20 transition-all duration-300 transform hover:scale-[1.02]">
                    <h2 className="text-3xl font-bold mb-6 text-black">About Me</h2>
                    <p className="text-black text-lg leading-relaxed mb-4">
                        I'm a passionate student at the University of Victoria studying Computer Science and Math.
                    </p>
                    <p className="text-black text-lg leading-relaxed">
                    I'm passionate about encouraging women to pursue STEM, and advocating for STEM spaces to be more inclusive and welcoming.
                    </p>
                </div>

                {/* GITHUB CHART! */}
                <div className="mb-20 bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-white/20 transition-all duration-300">
                    <h2 className="text-3xl font-bold mb-6 text-black">GitHub Activity</h2>
                    <p className="text-black">My github chart! I've spent the last year working on a variety of projects!</p>
                    <div className="rounded-lg overflow-hidden bg-white/5 p-4">
                        <img
                            src="https://ghchart.rshah.org/charliharrold"
                            alt="GitHub Contribution Chart"
                            className="w-full"
                            style={{ imageRendering: 'crisp-edges' }}
                        />
                    </div>
                </div>

                {/* Fun Facts */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {[
                        { emoji: '⚖️', title: 'Advocacy', desc: 'DETAILS FROM CLUBS' },
                        { emoji: '🚀', title: 'Projects', desc: '50+ completed' },
                        { emoji: '🎵', title: 'Playlists', desc: '100+ hours' },
                    ].map((fact, index) => (
                        <div
                            key={index}
                            className="bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10 text-center transform hover:scale-105 hover:rotate-1 transition-all duration-300 cursor-pointer"
                        >
                            <div className="text-5xl mb-3">{fact.emoji}</div>
                            <h3 className="text-xl font-bold mb-2">{fact.title}</h3>
                            <p className="text-black">{fact.desc}</p>
                        </div>
                    ))}
                </div>

            </div>
        </div>
    );
}